Обратная сторона реальности
htmlacademy-react/1666943-what-to-watch-8 pull request #5
Opened 2021-10-18 09:11 UTC by Askema

---
:mortar_board: [Обратная сторона реальности](https://up.htmlacademy.ru/react/8/user/1666943/tasks/5)

2021-10-20 17:50 UTC, slyvkanychmykyta requested changes

2021-10-20 17:50 UTC, slyvkanychmykyta commented on project/src/components/film-list/film-list.tsx
> +import FilmCard from '../film-card/film-card';
а тут уже импортируется FilmCard, видимо опечатался

2021-10-20 17:50 UTC, slyvkanychmykyta commented on project/src/types/film.ts
> +export type Films = Film[];
в принципе, films отдельно создавать не обязательно, данный тип можно объявить уже в компоненте

2021-10-20 17:50 UTC, slyvkanychmykyta commented on project/src/components/add-review-form/add-review-form.tsx
> +function RatingElement(props: RatingElementProps): JSX.Element {
это отдельный компонент, здесь ему нечего делать) RatingStar будет более подходящее название

2021-10-20 17:50 UTC, slyvkanychmykyta commented on project/src/components/add-review-page/AddReviewPage.tsx
> +  if (film !== undefined) {
`if (film) {return .... }; 
return <NotFoundPage />`. Можно без else

2021-10-31 15:24 UTC, Askema commented on project/src/components/film-list/film-list.tsx
> +  const [, setActiveCard] = useState({});
Если передать в useState null, то он будет всегда ожидать именно null, то есть перезаписать стейт в объект потом не получится

2021-11-01 17:26 UTC, slyvkanychmykyta requested changes

2021-11-01 17:26 UTC, slyvkanychmykyta commented on project/src/components/rating-star/rating-star.tsx
> +const AddReviewRatingStars: number[] = new Array(10).fill('').map((_, index) => index+1).reverse();
проще будет использовать `Array.from`: 
`Array.from({ length: 10 }, (v, k) => k);`.

2021-11-01 17:26 UTC, slyvkanychmykyta commented on project/src/components/add-review-form/add-review-form.tsx
> +        <textarea className="add-review__textarea" name="review-text" id="review-text" placeholder="Review text"
это видимо пропустил

2021-11-01 17:26 UTC, slyvkanychmykyta commented on project/src/components/film-list/film-list.tsx
> +  const [, setActiveCardId] = useState({});
чтобы положить сюда null, нужно `useState<number | null>(null)`

2021-11-01 17:26 UTC, slyvkanychmykyta commented on project/src/components/film-page/FilmPage.tsx
> +  if (film !== undefined) {
if (film)  {...}

2021-11-01 17:26 UTC, slyvkanychmykyta commented on project/src/components/my-list-page/MyListPage.tsx
> +                  setActiveCard([{}]);
setActiveCard(null)

2021-11-01 17:26 UTC, slyvkanychmykyta commented on project/src/components/my-list-page/MyListPage.tsx
> +  const [, setActiveCard] = useState({});
обычно присваивается id, а не целый объект useState<number | null>(null)

2021-11-01 17:26 UTC, slyvkanychmykyta commented on project/src/components/my-list-page/MyListPage.tsx
> +              <article key={keyValue} className="small-film-card catalog__films-card"
эта часть разметки должна быть в карточке фильма, а в карточку фильма уже прокинется  `setActiveCardId` и `activeCardId`. И в компоненте решается, допустим, нужно ли что-то делать с карточкой или нет, в зависимости от того активная она или нет

2021-11-02 17:17 UTC, slyvkanychmykyta approved these changes

2021-11-02 17:17 UTC, merged